### ISSUE TITLE
Adding a filter to Rx 2.x Subjects, Processors, and Observables converted to Rx 1.x Observables throws an exception.

### ISSUE THREAD

**Issue by tonycosentini** [akarnokd/RxJava2Interop#10]
Repro snippet:
```java
BehaviorSubject<String> subject = BehaviorSubject.create();

 rx.Observable<String> v1Observable = toV1Observable(subject, BackpressureStrategy.BUFFER)
            .filter(new Func1<String, Boolean>() {
                @Override
                public Boolean call(String s) {
                    return s.length() > 0;
                }
            });

v1Observable.subscribe();
```

Results in this stacktrace (RxJavaInteropTest.java:790 corresponds with the `subscribe()` call in the repro snippet above):
```
java.lang.IllegalArgumentException: n > 0 required but it was 0
	at io.reactivex.internal.subscriptions.SubscriptionHelper.validate(SubscriptionHelper.java:80)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:228)
	at hu.akarnokd.rxjava.interop.FlowableV2ToObservableV1$SourceSubscriber.request(FlowableV2ToObservableV1.java:60)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeFilter$FilterSubscriber.setProducer(OnSubscribeFilter.java:103)
	at hu.akarnokd.rxjava.interop.FlowableV2ToObservableV1.call(FlowableV2ToObservableV1.java:38)
	at hu.akarnokd.rxjava.interop.FlowableV2ToObservableV1.call(FlowableV2ToObservableV1.java:25)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:45)
	at rx.internal.operators.OnSubscribeFilter.call(OnSubscribeFilter.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:9980)
	at hu.akarnokd.rxjava.interop.RxJavaInteropTest.bugRepro(RxJavaInteropTest.java:790)
```

Removing the filter doesn't trigger the crash. This also reproduces when converting Rx 2.x processors and observables.

Let me know if there are more details that would help with this or if I'm misusing the API.

Thanks!

**Comment by akarnokd** [comment]
Thanks, forgot that 1.x can request 0 legally but it is illegal in 2.0. Will post a new version shortly.

**Comment by akarnokd** [comment]
Closing via [v0.7.2](https://github.com/akarnokd/RxJava2Interop/releases/tag/v0.7.2)

**Comment by tonycosentini** [comment]
Thanks!
