### ISSUE TITLE
Crash when used with SQLBrite

### ISSUE THREAD

**Issue by agramian** [akarnokd/RxJava2Interop#12]
I'm getting a crash when using the library with [SQLBrite](https://github.com/square/sqlbrite) in release mode.  Are there any required proguard rules for the RxJava2Interop?

```
02-07 17:10:50.719 18280-18280/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.test, PID: 18280
                                                   java.lang.InternalError
                                                       at j.c.e.b.k.a(UnsafeAccess.java:115)
                                                       at j.c.e.b.j.<clinit>(SpscArrayQueue.java:42)
                                                       at j.c.a.j$a.<init>(OperatorObserveOn.java:126)
                                                       at j.c.a.j.a(OperatorObserveOn.java:74)
                                                       at j.c.a.j.call(OperatorObserveOn.java:40)
                                                       at j.c.a.g.a(OnSubscribeLift.java:44)
                                                       at j.c.a.g.a(OnSubscribeLift.java:30)
                                                       at j.c.a.g.a(OnSubscribeLift.java:48)
                                                       at j.c.a.g.a(OnSubscribeLift.java:30)
                                                       at j.c.a.g.a(OnSubscribeLift.java:48)
                                                       at j.c.a.g.a(OnSubscribeLift.java:30)
                                                       at j.c.a(Observable.java:10144)
                                                       at com.c.b.a$4.a(BriteDatabase.java:387)
                                                       at com.c.b.a$4.a(BriteDatabase.java:385)
                                                       at j.c.a.g.a(OnSubscribeLift.java:48)
                                                       at j.c.a.g.a(OnSubscribeLift.java:30)
                                                       at j.c.a(Observable.java:10144)
                                                       at c.a.a.a.a.a(ObservableV1ToObservableV2.java:37)
                                                       at d.b.l.b(Observable.java:10685)
                                                       at d.b.e.e.d.k.a(ObservableFlattenIterable.java:44)
                                                       at d.b.l.b(Observable.java:10685)
                                                       at d.b.e.e.d.j.a(ObservableFlatMap.java:55)
                                                       at d.b.l.b(Observable.java:10685)
                                                       at d.b.e.e.d.k.a(ObservableFlattenIterable.java:44)
                                                       at d.b.l.b(Observable.java:10685)
                                                       at d.b.e.e.d.e.a(ObservableDoOnEach.java:42)
                                                       at d.b.l.b(Observable.java:10685)
                                                       at d.b.l.a(Observable.java:10671)
                                                       at d.b.l.h(Observable.java:10551)
                                                       at com.example.test.TestService.onCreate(TestServiceService.java:82)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2791)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:155)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                    Caused by: java.lang.NoSuchFieldException: producerIndex
                                                       at java.lang.Class.getDeclaredField(Class.java:890)
                                                       at j.c.e.b.k.a(UnsafeAccess.java:112)
                                                       at j.c.e.b.j.<clinit>(SpscArrayQueue.java:42) 
                                                       at j.c.a.j$a.<init>(OperatorObserveOn.java:126) 
                                                       at j.c.a.j.a(OperatorObserveOn.java:74) 
                                                       at j.c.a.j.call(OperatorObserveOn.java:40) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:44) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:30) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:48) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:30) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:48) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:30) 
                                                       at j.c.a(Observable.java:10144) 
                                                       at com.c.b.a$4.a(BriteDatabase.java:387) 
                                                       at com.c.b.a$4.a(BriteDatabase.java:385) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:48) 
                                                       at j.c.a.g.a(OnSubscribeLift.java:30) 
                                                       at j.c.a(Observable.java:10144) 
                                                       at c.a.a.a.a.a(ObservableV1ToObservableV2.java:37) 
                                                       at d.b.l.b(Observable.java:10685) 
                                                       at d.b.e.e.d.k.a(ObservableFlattenIterable.java:44) 
                                                       at d.b.l.b(Observable.java:10685) 
                                                       at d.b.e.e.d.j.a(ObservableFlatMap.java:55) 
                                                       at d.b.l.b(Observable.java:10685) 
                                                       at d.b.e.e.d.k.a(ObservableFlattenIterable.java:44) 
                                                       at d.b.l.b(Observable.java:10685) 
                                                       at d.b.e.e.d.e.a(ObservableDoOnEach.java:42) 
                                                       at d.b.l.b(Observable.java:10685) 
                                                       at d.b.l.a(Observable.java:10671) 
                                                       at d.b.l.h(Observable.java:10551) 
                                                       at com.example.test.Service.onCreate(Service.java:82) 
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2791) 
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:155) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1400) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5343) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
```

**Comment by agramian** [comment]
Nvm. Using this [RxJavaProGuardRules](https://github.com/artem-zinnatullin/RxJavaProGuardRules) seemed to resolve the issues.

**Comment by akarnokd** [comment]
The interop should be proguard friendly and doesn't need its own rules.
