### ISSUE TITLE
No such element exception being thrown 

### ISSUE THREAD

**Issue by KonradSzewczuk** [akarnokd/RxJava2Interop#25]
I am using the function like this:

    RxJavaInterop.toV2Flowable(
      method()
      .map{ Unit } )

where method() returns Observable<Void>

I am dealling with this exception being thrown:

```
> 11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter: java.util.NoSuchElementException
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableElementAtSingle$ElementAtSubscriber.onComplete(FlowableElementAtSingle.java:115)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:135)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableSkipWhile$SkipWhileSubscriber.onComplete(FlowableSkipWhile.java:83)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber.innerSuccess(FlowableFlatMapSingle.java:184)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableFlatMapSingle$FlatMapSingleSubscriber$InnerObserver.onSuccess(FlowableFlatMapSingle.java:364)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableElementAtSingle$ElementAtSubscriber.onNext(FlowableElementAtSingle.java:87)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at hu.akarnokd.rxjava.interop.ObservableV1ToFlowableV2$ObservableSubscriber.onNext(ObservableV1ToFlowableV2.java:62)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.accept(SubjectSubscriptionManager.java:317)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitLoop(SubjectSubscriptionManager.java:290)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitFirst(SubjectSubscriptionManager.java:269)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:109)
11-05 21:39:35.939 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.BehaviorSubject$1.call(BehaviorSubject.java:105)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager.add(SubjectSubscriptionManager.java:100)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:60)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at hu.akarnokd.rxjava.interop.ObservableV1ToFlowableV2.subscribeActual(ObservableV1ToFlowableV2.java:38)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.Flowable.subscribe(Flowable.java:13041)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.flowable.FlowableElementAtSingle.subscribeActual(FlowableElementAtSingle.java:41)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.Single.subscribe(Single.java:2779)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:70)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:116)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.completable.CompletableFromObservable$CompletableFromObservableObserver.onComplete(CompletableFromObservable.java:56)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onComplete(ObservableFromPublisher.java:46)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at hu.akarnokd.rxjava.interop.ObservableV1ToFlowableV2$ObservableSubscriber.onCompleted(ObservableV1ToFlowableV2.java:82)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onCompleted(OperatorOnErrorResumeNextViaFunction.java:101)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.observers.SerializedObserver.onCompleted(SerializedObserver.java:176)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.observers.SerializedSubscriber.onCompleted(SerializedSubscriber.java:64)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.drain(OnSubscribeConcatMap.java:246)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerCompleted(OnSubscribeConcatMap.java:209)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onCompleted(OnSubscribeConcatMap.java:345)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.NotificationLite.accept(NotificationLite.java:125)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.subjects.BehaviorSubject.onCompleted(BehaviorSubject.java:128)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.util.ObserverSubscriber.onCompleted(ObserverSubscriber.java:44)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:79)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.observers.Subscribers$5.onCompleted(Subscribers.java:225)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onCompleted(OnSubscribeDoOnEach.java:70)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:281)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:216)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at android.os.Handler.handleCallback(Handler.java:815)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at android.os.Handler.dispatchMessage(Handler.java:104)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at android.os.Looper.loop(Looper.java:194)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at android.app.ActivityThread.main(ActivityThread.java:5643)
11-05 21:39:35.940 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at java.lang.reflect.Method.invoke(Native Method)
11-05 21:39:35.941 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at java.lang.reflect.Method.invoke(Method.java:372)
11-05 21:39:35.941 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
11-05 21:39:35.941 29593-29593/com.hidglobal.tmt.app.verifier E/ActivationPresenter:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

What is causing the possible issue? In addition, i am getting this case only on several devices in compare to other

**Comment by akarnokd** [comment]
Without seeing some representative code of your issue, I can only guess that you have a `skipWhile` that skips all items due to wrong logic and a `first` operator in your chain simply doesn't get any items, thus failing with `NoSuchElementException`. 

It is unlikely this is a problem with the interop library as the stacktrace indicates it happily relayed the `onNext` item from the v1 `Observable`.
